site_name: EDS-NLP

repo_url: https://github.com/aphp/edsnlp
repo_name: aphp/edsnlp

# copyright: Copyright &copy; 2022 – Assistance Publique - Hôpitaux de Paris

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/aphp

theme:
  language: en
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  # logo: assets/logo/edsnlp.svg
  favicon: assets/logo/edsnlp.svg
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy

nav:
  - index.md
  - Demo: https://aphp.github.io/edsnlp/demo" target="_blank
  - Tutorials:
      - tutorials/index.md
      - tutorials/spacy101.md
      - tutorials/quick-examples.md
      - tutorials/matching-a-terminology.md
      - tutorials/qualifying-entities.md
      - tutorials/aggregating-results.md
      - tutorials/detecting-dates.md
      - tutorials/multiple-texts.md
      - tutorials/endlines.md
      - tutorials/reason.md
  - Advanced tutorials:
      - advanced-tutorials/index.md
      - advanced-tutorials/word-vectors.md
      - advanced-tutorials/fastapi.md
      - Creating a pipeline: https://spacy.io/usage/processing-pipelines#custom-components" target="_blank
  - Pipes:
      - Overview: pipelines/overview.md
      - Core Pipelines:
          - Overview: pipelines/core/overview.md
          - pipelines/core/normalizer.md
          - pipelines/core/sentences.md
          - pipelines/core/matcher.md
          - pipelines/core/terminology.md
          - pipelines/core/contextual-matcher.md
          - pipelines/core/endlines.md
      - Qualifiers:
          - Overview: pipelines/qualifiers/overview.md
          - pipelines/qualifiers/negation.md
          - pipelines/qualifiers/family.md
          - pipelines/qualifiers/hypothesis.md
          - pipelines/qualifiers/reported-speech.md
          - pipelines/qualifiers/history.md
      - Miscellaneous:
          - Overview: pipelines/misc/overview.md
          - pipelines/misc/index.md
          - pipelines/misc/dates.md
          - pipelines/misc/measurements.md
          - pipelines/misc/consultation-dates.md
          - pipelines/misc/sections.md
          - pipelines/misc/reason.md
          - pipelines/misc/tables.md
      - Named Entity Recognition:
          - Overview: pipelines/ner/overview.md
          - Scores:
            - Overview: pipelines/ner/scores/overview.md
            - pipelines/ner/scores/charlson.md
            - pipelines/ner/scores/emergency-ccmu.md
            - pipelines/ner/scores/emergency-gemsa.md
            - pipelines/ner/scores/emergency-priority.md
            - pipelines/ner/scores/sofa.md
            - pipelines/ner/scores/elston-ellis.md
          - Disorders:
            - Overview: pipelines/ner/disorders/overview.md
            - pipelines/ner/disorders/aids.md
            - pipelines/ner/disorders/ckd.md
            - pipelines/ner/disorders/copd.md
            - pipelines/ner/disorders/cerebrovascular-accident.md
            - pipelines/ner/disorders/congestive-heart-failure.md
            - pipelines/ner/disorders/connective-tissue-disease.md
            - pipelines/ner/disorders/dementia.md
            - pipelines/ner/disorders/diabetes.md
            - pipelines/ner/disorders/hemiplegia.md
            - pipelines/ner/disorders/leukemia.md
            - pipelines/ner/disorders/liver-disease.md
            - pipelines/ner/disorders/lymphoma.md
            - pipelines/ner/disorders/myocardial-infarction.md
            - pipelines/ner/disorders/peptic-ulcer-disease.md
            - pipelines/ner/disorders/peripheral-vascular-disease.md
            - pipelines/ner/disorders/solid-tumor.md
            - pipelines/ner/covid.md
          - Behaviors:
            - Overview: pipelines/ner/behaviors/overview.md
            - pipelines/ner/behaviors/alcohol.md
            - pipelines/ner/behaviors/tobacco.md
          - pipelines/ner/adicap.md
          - pipelines/ner/tnm.md
          - pipelines/ner/umls.md
          - pipelines/ner/cim10.md
          - pipelines/ner/drugs.md

      - Trainable components:
          - pipelines/trainable/index.md
          - pipelines/trainable/ner.md
          - pipelines/trainable/span-qualifier.md
  - tokenizers.md
  - Connectors:
      - utilities/connectors/index.md
      - utilities/connectors/brat.md
      - utilities/connectors/omop.md
  - Utilities:
      - utilities/tests/index.md
      - utilities/tests/blocs.md
      - utilities/tests/examples.md
      - utilities/matchers.md
      - utilities/processing/spark.md
  - Code Reference: reference/
  - contributing.md
  - changelog.md

extra:
  version:
    provider: mike
    default: latest
#   Just uncomment the following lines to enable i18n
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Français
#       link: /fr/
#       lang: fr

extra_css:
  - assets/stylesheets/extra.css
  - assets/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - assets/termynal/termynal.js

watch:
  - contributing.md
  - changelog.md
  - edsnlp
  - docs/scripts

hooks:
    - docs/scripts/plugin.py

plugins:
  - search
  - autorefs:
      priority:
        - '*'
        - reference
  - mkdocstrings:
      enable_inventory: true
      custom_templates: docs/assets/templates
      handlers:
        python:
          options:
            extensions:
              - docs/scripts/griffe_ext.py:EDSNLPDocstrings
            docstring_style: numpy
            docstring_section_style: spacy
            heading_level: 2
            members_order: source
            show_root_toc_entry: false
            show_signature: false
            merge_init_into_class: true
  - autolinks
  - bibtex:
      bibtex_file: "docs/references.bib"
# Just uncomment the following lines to enable i18n
# and start creating .fr.md and .en.md files.
#  - i18n:
#      default_language: en
#      docs_structure: suffix
#      languages:
#        en:
#          name: English
#          build: true
  - mike

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

validation:
  absolute_links: ignore
