[project]
name = "edsnlp"
description = "A set of spaCy components to extract information from clinical notes written in French"
authors = [
    { name = "Data Science - DSN APHP", email = "perceval.wajsburt-ext@aphp.fr" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7.1"
dynamic = ['version']
dependencies = [
    "decorator",
    "loguru",
    "pendulum>=2.1.2",
    "pydantic>=1.10.2,<2.0.0",
    "pysimstring>=1.2.1",
    "regex",
    "rich>=12.0.0",
    "scikit-learn>=1.0.0",
    "spacy>=3.1,<3.5.0",
    "thinc>=8.1.10",
    "tqdm",
    "umls-downloader>=0.1.1",
    "numpy>=1.15.0,<1.23.2; python_version<'3.8'",
    "numpy>=1.15.0; python_version>='3.8'",
    "pandas>=1.1.0,<2.0.0; python_version<'3.8'",
    "pandas>=1.4.0,<2.0.0; python_version>='3.8'",
    "typing_extensions<4.6.0,>=4.0.0; python_version>='3.8'",  # https://github.com/explosion/spaCy/issues/12659
    "typing_extensions>=4.0.0; python_version<'3.8'"
]
[project.optional-dependencies]
dev = [
    "black>=22.3.0,<23.0.0",
    "fastapi",
    "flake8==3.9.2",
    "koalas>=1.8.1; python_version<='3.10'",
    "pre-commit>=2.0.0; python_version<'3.8'",
    "pre-commit>=2.21.0; python_version>='3.8'",
    "pyspark",
    "pytest>=7.1.0,<8.0.0",
    "pytest-cov>=3.0.0,<4.0.0",
    "pytest-html>=3.1.1,<4.0.0",
    "torch>=1.0.0",

    # docs
    "mike~=1.1.2",
    "mkdocs-charts-plugin==0.0.8",
    "mkdocs-img2fig-plugin==0.9.3",
    "mkdocs-material~=9.1.0",
    "mkdocs-section-index==0.3.4",
    "mkdocs~=1.5.2",
    "mkdocstrings~=0.20",
    "mkdocstrings-python~=1.1",
    "mkdocs-autolinks-plugin~=0.7.1",
    "pybtex~=0.24.0",
    "pathspec>=0.11.1",  # required by vendored mkdocs-autorefs PR
]
setup = [
    "mlconjug3<3.9.0",
    "typer"
]

[project.urls]
"Source Code" = "https://github.com/aphp/edsnlp"
"Documentation" = "https://aphp.github.io/edsnlp"
"Demo" = "https://aphp.github.io/edsnlp/demo"
"Bug Tracker" = "https://github.com/aphp/edsnlp/issues"

[tool.setuptools.dynamic]
version = { attr = "edsnlp.__version__" }

[tool.setuptools.package-data]
"edsnlp" = [
    "**/*.pyx",
    "**/*.pxd",
    "**/*.pxi",
    "resources/*.csv",
    "resources/*.json",
    "resources/*.csv.gz",
    "resources/*.json.gz",
]

[tool.setuptools.packages.find]
where = ["."]

[project.entry-points."spacy_factories"]
"eds.matcher" = "edsnlp.components:matcher"
"eds.terminology" = "edsnlp.components:terminology"
"eds.contextual_matcher" = "edsnlp.components:contextual_matcher"
"eds.endlines" = "edsnlp.components:endlines"
"eds.sentences" = "edsnlp.components:sentences"
"eds.normalizer" = "edsnlp.components:normalizer"
"eds.accents" = "edsnlp.components:accents"
"eds.lowercase" = "edsnlp.components:remove_lowercase"
"eds.pollution" = "edsnlp.components:pollution"
"eds.quotes" = "edsnlp.components:quotes"
"eds.charlson" = "edsnlp.components:charlson"
"eds.sofa" = "edsnlp.components:sofa"
"eds.tnm" = "edsnlp.components:tnm"
"eds.priority" = "edsnlp.components:priority"
"eds.ccmu" = "edsnlp.components:ccmu"
"eds.gemsa" = "edsnlp.components:gemsa"
"eds.covid" = "edsnlp.components:covid"
"eds.cim10" = "edsnlp.components:cim10"
"eds.history" = "edsnlp.components:history"
"eds.family" = "edsnlp.components:family"
"eds.hypothesis" = "edsnlp.components:hypothesis"
"eds.negation" = "edsnlp.components:negation"
"eds.rspeech" = "edsnlp.components:rspeech"
"eds.consultation_dates" = "edsnlp.components:consultation_dates"
"eds.dates" = "edsnlp.components:dates"
"eds.reason" = "edsnlp.components:reason"
"eds.sections" = "edsnlp.components:sections"
"eds.context" = "edsnlp.components:context"
"eds.measurements" = "edsnlp.components:measurements"
"eds.drugs" = "edsnlp.components:drugs"
"eds.nested_ner" = "edsnlp.components:nested_ner"
"eds.span_qualifier" = "edsnlp.pipelines.trainable.span_qualifier.factory:create_component"
"eds.adicap" = "edsnlp.components:adicap"
"eds.umls" = "edsnlp.components:umls"
"eds.diabetes" = "edsnlp.components:diabetes"
"eds.tobacco" = "edsnlp.components:tobacco"
"eds.aids" = "edsnlp.components:AIDS"
"eds.lymphoma" = "edsnlp.components:lymphoma"
"eds.leukemia" = "edsnlp.components:leukemia"
"eds.solid_tumor" = "edsnlp.components:solid_tumor"
"eds.ckd" = "edsnlp.components:CKD"
"eds.hemiplegia" = "edsnlp.components:hemiplegia"
"eds.liver_disease" = "edsnlp.components:liver_disease"
"eds.peptic_ulcer_disease" = "edsnlp.components:peptic_ulcer_disease"
"eds.connective_tissue_disease" = "edsnlp.components:connective_tissue_disease"
"eds.copd" = "edsnlp.components:COPD"
"eds.dementia" = "edsnlp.components:dementia"
"eds.cerebrovascular_accident" = "edsnlp.components:cerebrovascular_accident"
"eds.peripheral_vascular_disease" = "edsnlp.components:peripheral_vascular_disease"
"eds.congestive_heart_failure" = "edsnlp.components:congestive_heart_failure"
"eds.myocardial_infarction" = "edsnlp.components:myocardial_infarction"
"eds.alcohol" = "edsnlp.components:alcohol"

[project.entry-points."spacy_architectures"]
"eds.stack_crf_ner_model.v1" = "edsnlp.pipelines.trainable.nested_ner.stack_crf_ner:create_model"
"eds.span_multi_classifier.v1" = "edsnlp.pipelines.trainable.span_qualifier.span_multi_classifier:create_model"

[project.entry-points."spacy_scorers"]
"eds.nested_ner_scorer.v1" = "edsnlp.pipelines.trainable.nested_ner.nested_ner:make_nested_ner_scorer"
"eds.span_qualifier_scorer.v1" = "edsnlp.pipelines.trainable.span_qualifier.factory:create_scorer"

[project.entry-points."spacy_misc"]
"eds.candidate_span_qualifier_getter" = "edsnlp.pipelines.trainable.span_qualifier.factory:create_candidate_getter"

[project.entry-points."spacy_languages"]
"eds" = "edsnlp.language:EDSLanguage"

[project.entry-points."mkdocs.plugins"]
"bibtex" = "docs.scripts.bibtex:BibTexPlugin"
"autorefs" = "docs.scripts.autorefs.plugin:AutorefsPlugin"

[build-system]
requires = [
    "setuptools",
    "cython>=0.25,<3.0",
    "spacy>=3.2,<4.0",
    # to update from https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
    # while setting numpy >= 1.15.0 due to spacy reqs
    "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'",
    "numpy==1.23.3; python_version=='3.9' and platform_system=='OS400'",
    "numpy==1.19.2; python_version=='3.7' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy'",
    "numpy==1.19.2; python_version=='3.8' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy'",
    "numpy==1.21.0; python_version=='3.7' and platform_machine=='arm64' and platform_system=='Darwin'",
    "numpy==1.21.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin'",
    "numpy==1.21.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin'",
    "numpy==1.17.5; python_version=='3.8' and platform_machine=='s390x' and platform_python_implementation != 'PyPy'",
    "numpy==1.22.2; platform_machine=='loongarch64' and python_version<'3.11'",
    "numpy==1.15.0; python_version=='3.7' and platform_machine not in 'arm64|aarch64|loongarch64' and platform_system!='AIX' and platform_python_implementation != 'PyPy'",
    "numpy==1.17.3; python_version=='3.8' and platform_machine not in 'arm64|aarch64|s390x|loongarch64' and platform_python_implementation != 'PyPy'",
    "numpy==1.19.3; python_version=='3.9' and platform_system not in 'OS400' and platform_machine not in 'arm64|loongarch64' and platform_python_implementation != 'PyPy'",
    "numpy==1.21.6; python_version=='3.10' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",
    "numpy==1.20.0; python_version=='3.7' and platform_machine!='loongarch64' and platform_python_implementation=='PyPy'",
    "numpy==1.22.2; python_version=='3.8' and platform_machine!='loongarch64' and platform_python_implementation=='PyPy'",
    "numpy; python_version>='3.12'",
    "numpy; python_version>='3.9' and platform_python_implementation=='PyPy'",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
fix = true
extend-exclude = [
    ".git",
    "__pycache__",
    "__init__.py",
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    "build",
    "edsnlp/pipelines/factories.py",
]
line-length = 88
select = [
    "E",
    "F",
    "W",
    "I001"
]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "parents"

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]
"edsnlp/pipelines/factories.py" = [ "F401", "E501" ]

[tool.ruff.isort]
known-first-party = ["edsnlp"]
order-by-type = true

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 40
exclude = ["setup.py", "docs", "build", "tests"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
omit-covered-files = false
# generate-badge = "."
# badge-format = "svg"


[tool.coverage]
exclude_lines = [
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
    "@overload",
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "def __repr__",
    "Span.set_extension.*",
    "Doc.set_extension.*",
    "Token.set_extension.*",
]

[tool.cibuildwheel]
skip = [
    "*p36-*", # Skip Python 3.6
    "pp*", # Skip PyPy
    "*-win32", # Skip 32-bit Windows
    "*-manylinux_i686", # Skip 32-bit Linux
    "*-win_arm64", # Skip experimental Windows on ARM
    "*-musllinux*", # Skip slow Linux
    "*-manylinux_aarch64", # Skip slow Linux
    "*-manylinux_ppc64le", # Skip slow Linux
    "*-manylinux_s390x", # Skip slow Linux
]

before-test = "pip install pytest"
test-command = "pytest {project}/tests/pipelines/test_pipelines.py"
